name: CI/CD

on:
  push:
    branches:
      - master

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.json') }}

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
